### ISSUE TITLE
hOCR: List graphics elements where they appear in the page between paragraphs, not at the page end.

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#233]

**Comment by manisandro** [comment]
@SantosSi Please try with the latest master with the Qt interface (see compile HOWTO).

**Comment by SantosSi** [comment]
Very nice, thank you.

**Comment by ZaMaZaN4iK** [comment]
@manisandro can we close the issue?

**Comment by manisandro** [comment]
Gtk is missing

**Comment by manisandro** [comment]
Done also fro gtk.

**Comment by SantosSi** [comment]
Images detected by OCR appear where 
they belong within the other elements, 
but manually created ones ("Add graphic 
region") still appear at the end.

**Comment by manisandro** [comment]
Mhh what would the logic be? Above the first box which starts below the bottom border of the image?

**Comment by SantosSi** [comment]
Yes and in LTR orientation before the 
line when the image is left of the text 
and after the text when it's right to it. 
And vice versa in RTL orientation.

**Comment by manisandro** [comment]
Well graphics live at block level, so they know nothing about text lines.
