### ISSUE TITLE
3.3.4 candidate does not compile on Debian Bookworm

### ISSUE THREAD

**Issue by SantosSi** [manisandro/gImageReader#560]
On Debian Testing Bookworm with the newest master c116153 (candidate for 3.3.4) the following error is thrown:
```

CMake Error at CMakeLists.txt:168 (FIND_PACKAGE):
  By not providing "FindQuaZip-Qt5.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "QuaZip-Qt5", but CMake did not find one.

  Could not find a package configuration file provided by "QuaZip-Qt5" with
  any of the following names:

    QuaZip-Qt5Config.cmake
    quazip-qt5-config.cmake

  Add the installation prefix of "QuaZip-Qt5" to CMAKE_PREFIX_PATH or set
  "QuaZip-Qt5_DIR" to a directory containing one of the above files.  If
  "QuaZip-Qt5" provides a separate development package or SDK, be sure it has
  been installed.

```

Installed package libquazip5-dev provides: /usr/share/quazip/QuaZip5Config.cmake

**Comment by manisandro** [comment]
Should be fixed https://github.com/manisandro/gImageReader/commit/ac4117dab8b4bed100acd338cf4d8935a2f82ff4

**Comment by SantosSi** [comment]
Confirmed: it compiles successfully, although the error message still appears followed by:
`CMake Warning (dev) at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (QUAZIP)
  does not match the name of the calling package (QuaZip5).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/share/quazip/QuaZip5Config.cmake:42 (find_package_handle_standard_args)
  CMakeLists.txt:172 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.
`

**Comment by manisandro** [comment]
This is an issue in the `QuaZip5Config.cmake` - cmake would expect it to set `QuaZip5_FOUND`, but it sets `QUAZIP_FOUND` instead.
