### ISSUE TITLE
In hOCR mode, words with some punctuation marks are red

### ISSUE THREAD

**Issue by CharlesNepote** [manisandro/gImageReader#93]
A very small issue: in the tree of contents (right pannel), when a word end with a comma or semi-comma or a parenthesis, etc., it is considered as a mistake and shown in red. The issue doesn't occur when there is a dot.

Examples:
* ideas. => shown in black (OK)
* idzas => shown in red (OK)
* ideas, => red (KO)
* ideas; => red (KO)
* ideas) => red (KO)
* (ideas => red (KO)
* "ideas => red (KO)
* ideas" => red (KO)
* ex- => red (KO) (from ex-libris word at the end of a line)

It's not very important but it makes the correction of a document longuer as we can't see quickly all the real mistakes.

**Comment by manisandro** [comment]
Yeah I'll look at improving this.

**Comment by manisandro** [comment]
Fixed in dc596f0

**Comment by CharlesNepote** [comment]
The issue is partially resolved but still occurs with opening parenthesis, quotes, etc.:
* ideas) => black (OK)
* (ideas => red (KO)
* ideas" => black (OK)
* "ideas => red (KO)
* ideas' => black (OK)
* 'ideas => red (KO)
* ideas] => black (OK)
* [ideas => red (KO)
* ideas} => black (OK)
* {ideas => red (KO)

**Comment by manisandro** [comment]
Should be resolved for good with a7b9855
